name: Build VLCKit

on: 
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'vlckit source url you want to build'
        required: false

jobs:
  build_platforms:
    runs-on: macos-14
    strategy:
      matrix:
        platform: [macos, ios, tvos, watchos, xros]
        include:
          - platform: macos
            build_args: "-rx"
            package_args: "-x"
          - platform: ios
            build_args: "-rf" 
            package_args: "-vm"
          - platform: tvos
            build_args: "-rft"
            package_args: "-vt"
          - platform: watchos
            build_args: "-rfw"
            package_args: "-vw"
          - platform: xros
            build_args: "-rfi"
            package_args: "-vi"
    steps:
      - name: 🛠️ Checkout repository
        run: |
          git clone https://github.com/saltpi/vlckit-sdk.git VLCKit

      - name: 🖥️ Select Xcode version
        run: |
          ls /Applications/

      - name: 🚀 Build for ${{ matrix.platform }}
        run: |
          cd VLCKit
          ./compileAndBuildVLCKit.sh ${{ matrix.build_args }}
          ./Packaging/create-distributable-package.sh ${{ matrix.package_args }}

      - name: 🖥️ List artifact
        run: |
           ls .
           ls VLCKit

      - name: 📤 Upload ${{ matrix.platform }} Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VLCKit-${{ matrix.platform }}
          path: VLCKit/VLCKit-*.tar.xz

  list_artifacts:
    permissions:
      contents: write
    runs-on: macos-14
    needs: build_platforms
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: 📥 Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 📋 List built artifacts
        run: |
          echo "=== All built artifacts ==="
          find artifacts -name "*.xz" -o -name "*.zip" | sort
          echo "=== File details ==="
          ls -la artifacts/*/
          find . -name "make-xcframework.sh"|xargs -I % chmod +x %
          find . -name "make-xcframework.sh"|bash
          
      - name: 📤 Upload VLCKit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VLCKitSPM
          path: ./*.xcframework

      - name: Set date version
        id: set_version
        run: |
          DATE_VERSION=$(date +'%Y.%m.%d')
          echo "DATE_VERSION=$DATE_VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $DATE_VERSION"
      
      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.set_version.outputs.DATE_VERSION }}
          tag_name: ${{ steps.set_version.outputs.DATE_VERSION }}
          files: |
            *.xcframework.zip
          prerelease: false
          body_path: /tmp/RELEASE_NOTE.txt
          generate_release_notes: true
          fail_on_unmatched_files: true
