name: Build HarmonyOS ffmpeg

on: 
  workflow_dispatch:
    inputs:
      ffmpeg_url:
        description: 'ffmpeg source url you want to build'
        required: false

jobs:
  params:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Download SDK
        shell: bash
        continue-on-error: true
        run: |
          wget https://gitee.com/link?target=http%3A%2F%2Fdownload.ci.openharmony.cn%2Fversion%2FMaster_Version%2FOpenHarmony_4.0.11.3_Mr%2F20230822_020105%2Fversion-Master_Version-OpenHarmony_4.0.11.3_Mr-20230822_020105-ohos-sdk-full.tar.gz -O ohos-sdk.tar.gz
          wget https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n8.0.zip
          tar -xvf ohos-sdk.tar.gz
          unzip ohos-sdk/linux/native-linux-x64-4.0.10.5-Release.zip
          unzip n8.0.zip
  
      - name: Build
        shell: bash
        run: |
          ls
          ls Builder
          ls Builder/Builder
          cp Builder/Builder/ohos/build.sh build.sh
          cp Builder/Builder/ohos/aarch64-linux-ohos-clang ohos-sdk/linux/native/llvm/bin/aarch64-linux-ohos-clang
          chmod +x ohos-sdk/linux/native/llvm/bin/aarch64-linux-ohos-clang
          chmod +x build.sh
          cd FFmpeg-n8.0
          ../build.sh
          
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: FFmpeg-n8.0/harmonyos
