name: Download Huggingface Model

on: 
  workflow_dispatch:
    inputs:
      repo_id:
        description: 'the repo you want to download(e.g., org-name/project-name)'
        required: true

jobs:
  params:
    runs-on: ubuntu-latest
    steps:
      - name: Download using huggingface-cli
        if: ${{ inputs.repo_id != '' }}
        shell: bash
        continue-on-error: true
        run: |
          pip install -U "huggingface_hub[cli]"
          mkdir -p ${{ inputs.repo_id }}
          hf download ${{ inputs.repo_id }} --include "*" --local-dir ${{ inputs.repo_id }}
      
      - name: Upload using Rclone
        shell: bash
        run: |
          rm -rf ${{ inputs.repo_id }}/.cache
          rm -rf ${{ inputs.repo_id }}/.git
          python -m pip install requests tqdm
          wget https://drive.ourfor.top/tools/upload_session.py -O /tmp/upload.py
          find ${{ inputs.repo_id }} -type f | xargs -I % echo -e 'https://drive.ourfor.top/od_bot/model/%\n out=%' > url.txt
          cp url.txt ${{ inputs.repo_id }}/manifest.txt
          find ${{ inputs.repo_id }} -type f | xargs -I % python /tmp/upload.py --url 'https://drive.ourfor.top/od_bot/model/%' --token '${{ secrets.UPLOAD_SECRET }}' --file '%'

          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: url.txt
