name: Download Huggingface Model

on: 
  workflow_dispatch:
    inputs:
      repo_id:
        description: 'the repo you want to download(e.g., org-name/project-name)'
        required: true

jobs:
  params:
    runs-on: ubuntu-latest
    steps:
      - name: Download using huggingface-cli
        if: ${{ inputs.repo_id != '' }}
        shell: bash
        continue-on-error: true
        run: |
          pip install -U "huggingface_hub[cli]"
          mkdir -p ${{ inputs.repo_id }}
          hf download ${{ inputs.repo_id }} --include "*" --local-dir ${{ inputs.repo_id }}
      
      - name: Upload using Rclone
        shell: bash
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash
          echo "${{ secrets.RCLONE_CONFIG }}" | base64 -d > rclone.conf
          rm -rf ${{ inputs.repo_id }}/.cache
          rm -rf ${{ inputs.repo_id }}/.git
          find ${{ inputs.repo_id }} -type f | xargs -I % echo 'https://drive.ourfor.top/od_bot/model/%' > url.txt
          find ${{ inputs.repo_id }} -type f | xargs -I % python /tmp/upload.py --url "https://drive.ourfor.top/od_bot/model/%" --token "${{ secrets.UPLOAD_SECRET }}" --file "%"
          # rclone --config rclone.conf -P --onedrive-chunk-size 100M --transfers=6 move ${{ inputs.repo_id }} OneDrive:/model/${{ inputs.repo_id }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          path: url.txt
